# Generated by Django 5.2.7 on 2025-11-09 04:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('soltera', 'Soltera'), ('casada', 'Casada'), ('viuda', 'Viuda'), ('divorciada', 'Divorciada'), ('conviviente', 'Conviviente')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('prevision', models.CharField(choices=[('fonasa_a', 'Fonasa A'), ('fonasa_b', 'Fonasa B'), ('fonasa_c', 'Fonasa C'), ('fonasa_d', 'Fonasa D'), ('isapre', 'Isapre'), ('particular', 'Particular'), ('prais', 'PRAIS'), ('otra', 'Otra')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madres_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_parto', models.CharField(choices=[('vaginal', 'Vaginal'), ('cesarea', 'Cesárea'), ('forceps', 'Fórceps')], max_length=20)),
                ('semanas_gestacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)])),
                ('tipo_anestesia', models.CharField(choices=[('ninguna', 'Ninguna'), ('local', 'Local'), ('epidural', 'Epidural'), ('raquidea', 'Raquídea'), ('general', 'General')], max_length=20)),
                ('complicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_registrados', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='registros.madre')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_nacimiento', models.TimeField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(6.0)])),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)])),
                ('apgar_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('estado', models.CharField(choices=[('vivo', 'Vivo'), ('fallecido', 'Fallecido')], default='vivo', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='registros.parto')),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
            },
        ),
    ]
