# Generated by Django 5.2.7 on 2025-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='hora_nacimiento',
            field=models.TimeField(db_index=True),
        ),
    ]
