# Generated by Django 5.2.7 on 2025-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text='Max number of times this code can be used. Null = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='uses_count',
            field=models.IntegerField(default=0),
        ),
    ]
