# Generated by Django 5.2.8 on 2025-11-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_invitecode_expires_at_invitecode_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='run',
            field=models.CharField(blank=True, help_text='RUN sin puntos, con guión y dígito verificador', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
