# Generated by Django 5.2.8 on 2025-11-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('matrona', 'Matrona'), ('usuario', 'Usuario'), ('administrador', 'Administrador'), ('etc', 'ETC')], default='usuario', max_length=20),
        ),
    ]
